name: Build & Push Docker image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Option simple: version lue depuis un petit fichier "VERSION" si présent, sinon 1.0.0
      - name: Extract simple version
        id: vars
        run: |
          if [ -f VERSION ]; then V=$(cat VERSION); else V=1.0.0; fi
          echo "VERSION=$V" >> $GITHUB_OUTPUT
          echo "SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            chaouky/demo-spring:${{ steps.vars.outputs.VERSION }}
            chaouky/demo-spring:${{ steps.vars.outputs.VERSION }}-${{ steps.vars.outputs.SHA_SHORT }}
            chaouky/demo-spring:latest
